### ISSUE TITLE
VOTE: use selection to choose models for export instead exporting everything

### ISSUE THREAD

**Issue by neumond** [neumond/blender-md3#12]
This is a voting, please smile-react this post:
👍 — Yes, use selections.
👎 — No, export everything (current implementation).

If you have some suggestion or opinion feel free to add a comment.

**Comment by KillPixelGames** [comment]
+1 for export selection/visible

...and +1 for animated tags :D

**Comment by neumond** [comment]
I've received the PR with export visible option yesterday, I guess it deserves separate option.
By the way, animated tags were implemented.

**Comment by neumond** [comment]
Alternatively, I think it's possible to add plugin settings with all these options, so the user can choose desired behaviour. Anyway, it still needs some default value.

**Comment by KillPixelGames** [comment]
I would say export visible would be suitable for default behavior.  As far as animated tags goes, I must have missed that since I'm using an older version of the exporter since I couldn't get the most recent one to work with the latest blender version (2.79).

**Comment by neumond** [comment]
Hmm.. I'll test it myself in a day or two, it should be working.

**Comment by KillPixelGames** [comment]
Awesome.  Apologies for bringing that up in this thread.  I've been meaning to further debug and make a request.

**Comment by KillPixelGames** [comment]
I've got the latest exporter working with the latest blender (2.79b) but still cannot get the tags to animate - they show up in the resulting md3 but are static.  Perhaps I'm just overlooking something?

EDIT:  I'm able to export the test_tag.blend just fine (animated tags and all).  But tags parented to bones/or vertices don't seem to work.

**Comment by mynkijames** [comment]
KillPixelGames, just wanted to mention in Blender 2.79b I was able to export animated Tags which were parented to bones (and not directly keyed) by using Animation->Action:->Bake Action on the Tags just before export (be sure to save a backup copy before doing it so you can go back and edit things). For the Bake Action options I toggled Only Selected, Visual Keying, Clear Parents and chose Bake Data:Object. Not sure if they're all necessary, but it worked for me.

**Comment by KillPixelGames** [comment]
ah, baking the animation worked.  thank you!
